version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    # A porta não é exposta diretamente, o que é mais seguro. O Traefik fará o acesso.
    command: >
      poetry run uvicorn main:app
      --host 0.0.0.0
      --port ${BACKEND_PORT}
    labels:
      - "traefik.enable=true"
      # O Traefik irá descobrir a rede automaticamente.
      - "traefik.http.routers.s2c-back.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.s2c-back.entrypoints=websecure"
      - "traefik.http.routers.s2c-back.tls.certresolver=letsencrypt"
      - "traefik.http.services.s2c-back.loadbalancer.server.port=${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # As URLs públicas são mantidas, pois são obrigatórias para o frontend no navegador.
        VITE_HTTP_BACKEND_URL: ${VITE_HTTP_BACKEND_URL}
        VITE_WS_BACKEND_URL: ${VITE_WS_BACKEND_URL}
    env_file:
      - .env
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      # O Traefik irá descobrir a rede automaticamente.
      - "traefik.http.routers.s2c-front.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.s2c-front.entrypoints=websecure"
      - "traefik.http.routers.s2c-front.tls.certresolver=letsencrypt"
      - "traefik.http.services.s2c-front.loadbalancer.server.port=5173"

